export type FreeTool = {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  inputLabel: string;
  inputPlaceholder: string;
  prompt: (input: string) => string;
  outputLabel: string;
};

export const tools: FreeTool[] = [
  {
    slug: "tagline-generator",
    name: "Tagline Generator",
    tagline: "10 punchy taglines in 5 seconds.",
    description: "Drop in what your product does. Get 10 founder-grade taglines you can ship today.",
    inputLabel: "What does your product do?",
    inputPlaceholder: "e.g. AI writing assistant for marketers",
    outputLabel: "10 Taglines",
    prompt: (i) => `Generate 10 punchy, founder-grade taglines for this product: "${i}". Each tagline max 7 words, verb-led, no jargon. Return as a numbered list 1-10.`,
  },
  {
    slug: "value-prop-generator",
    name: "Value Prop Generator",
    tagline: "A crisp value proposition in one sentence.",
    description: "Turn what you do into a value prop people remember.",
    inputLabel: "Describe your product",
    inputPlaceholder: "e.g. Time-tracking for freelancers",
    outputLabel: "Value Proposition",
    prompt: (i) => `Write 3 value propositions for: "${i}". Each must follow the format: "We help [audience] do [outcome] without [pain]." Return as a numbered list 1-3.`,
  },
  {
    slug: "brand-name-generator",
    name: "Brand Name Generator",
    tagline: "15 short, ownable brand names.",
    description: "Two syllables, brandable, .com or .ai friendly.",
    inputLabel: "What's your product about?",
    inputPlaceholder: "e.g. A habit tracker for couples",
    outputLabel: "15 Brand Name Ideas",
    prompt: (i) => `Generate 15 brand name ideas for: "${i}". Rules: 2 syllables max, easy to spell, no numbers, no "ly" suffix. Return as a numbered list with a short rationale for each.`,
  },
  {
    slug: "positioning-statement-generator",
    name: "Positioning Statement Generator",
    tagline: "A complete positioning statement using April Dunford's framework.",
    description: "Category, audience, alternatives, differentiator — locked in.",
    inputLabel: "Describe your product and your competitors",
    inputPlaceholder: "e.g. We're a Notion alternative for designers...",
    outputLabel: "Positioning Statement",
    prompt: (i) => `Using April Dunford's positioning framework, write a complete positioning statement for: "${i}". Include: competitive alternatives, unique attributes, value, best-fit customer, and market category. Format as labeled sections.`,
  },
  {
    slug: "elevator-pitch-generator",
    name: "Elevator Pitch Generator",
    tagline: "3 sentences that win the room.",
    description: "Audience + outcome + differentiator. Ready to memorize.",
    inputLabel: "Describe your product",
    inputPlaceholder: "e.g. Stripe for podcast sponsorships",
    outputLabel: "Elevator Pitch",
    prompt: (i) => `Write a 3-sentence elevator pitch for: "${i}" using the format: "We help [audience] do [outcome] without [pain]. Unlike [alternative], we [differentiator]. [Proof or vision sentence]." Provide 3 variations.`,
  },
  {
    slug: "product-hunt-tagline",
    name: "Product Hunt Tagline",
    tagline: "60-char taglines built for Product Hunt.",
    description: "Optimized for the PH feed: short, specific, scroll-stopping.",
    inputLabel: "Describe your product",
    inputPlaceholder: "e.g. AI branding co-pilot for indie hackers",
    outputLabel: "5 PH Taglines",
    prompt: (i) => `Write 5 Product Hunt taglines (max 60 chars each) for: "${i}". Scroll-stopping, specific, verb-led. Number them 1-5 and show the character count next to each.`,
  },
  {
    slug: "twitter-bio-generator",
    name: "Twitter / X Bio Generator",
    tagline: "A founder bio that gets replies.",
    description: "Who you help + what you ship + a dash of personality.",
    inputLabel: "Tell us about yourself and what you're building",
    inputPlaceholder: "e.g. Solo founder building an AI launch tool",
    outputLabel: "5 X Bios",
    prompt: (i) => `Write 5 X (Twitter) bios for this founder: "${i}". Rules: max 160 chars, who you help / what you ship / proof or personality, founder-led tone. Number them 1-5.`,
  },
  {
    slug: "linkedin-headline-generator",
    name: "LinkedIn Headline Generator",
    tagline: "A LinkedIn headline that opens doors.",
    description: "Professional but not corporate. Specific, not buzzwordy.",
    inputLabel: "Your role and what you build",
    inputPlaceholder: "e.g. Founder, building AI tools for marketers",
    outputLabel: "5 LinkedIn Headlines",
    prompt: (i) => `Write 5 LinkedIn headlines (max 220 chars) for: "${i}". Specific, outcome-driven, no buzzwords. Number them 1-5.`,
  },
  {
    slug: "mission-statement-generator",
    name: "Mission Statement Generator",
    tagline: "A mission statement worth tattooing.",
    description: "One sentence. No fluff. The reason you exist.",
    inputLabel: "What does your company do and why?",
    inputPlaceholder: "e.g. Help indie founders launch faster",
    outputLabel: "3 Mission Statements",
    prompt: (i) => `Write 3 mission statements for: "${i}". Each must be one sentence, max 20 words, no buzzwords. Number them 1-3.`,
  },
  {
    slug: "slogan-generator",
    name: "Slogan Generator",
    tagline: "Stickable slogans for ads, swag, and emails.",
    description: "5-word max, memorable, repeatable.",
    inputLabel: "What's your product?",
    inputPlaceholder: "e.g. A meditation app for engineers",
    outputLabel: "10 Slogans",
    prompt: (i) => `Generate 10 short slogans (max 5 words each) for: "${i}". Memorable, repeatable, sticker-worthy. Number them 1-10.`,
  },
  {
    slug: "about-us-generator",
    name: "About Us Generator",
    tagline: "An About page that doesn't feel corporate.",
    description: "Story-led, founder-voiced, 150 words.",
    inputLabel: "Tell us about your company and team",
    inputPlaceholder: "e.g. We're 2 friends building AI tools after work...",
    outputLabel: "About Us Copy",
    prompt: (i) => `Write a 150-word About Us page for: "${i}". Story-led, founder-voiced, warm, ends with a vision sentence. No corporate fluff.`,
  },
  {
    slug: "feature-benefit-rewriter",
    name: "Feature → Benefit Rewriter",
    tagline: "Turn boring features into outcomes that sell.",
    description: "Paste your feature list. Get benefits people actually want.",
    inputLabel: "Paste your feature list",
    inputPlaceholder: "e.g.\\n- Real-time sync\\n- API access\\n- 99.9% uptime",
    outputLabel: "Feature → Benefit",
    prompt: (i) => `Rewrite each of these features as a customer benefit (the outcome the user gets):\n${i}\nReturn as a markdown table with columns: Feature | Benefit.`,
  },
  {
    slug: "cold-email-generator",
    name: "Cold Email Generator",
    tagline: "A 4-line cold email that gets replies.",
    description: "Hyper-specific subject, tiny ask, no fluff.",
    inputLabel: "Who are you emailing and about what?",
    inputPlaceholder: "e.g. Marketing director at a Series A SaaS, about our AI writing tool",
    outputLabel: "Cold Email",
    prompt: (i) => `Write a 4-line cold email for this scenario: "${i}". Format: Subject line + 4 short body lines. Line 1: specific observation. Line 2: relevance. Line 3: proof. Line 4: tiny ask.`,
  },
  {
    slug: "landing-headline-generator",
    name: "Landing Page Headline Generator",
    tagline: "10 hero headlines for your landing page.",
    description: "Each one optimized for clarity-first, scroll-stopping power.",
    inputLabel: "Describe your product",
    inputPlaceholder: "e.g. AI co-pilot that launches your app for you",
    outputLabel: "10 Headlines",
    prompt: (i) => `Generate 10 landing page hero headlines for: "${i}". Each max 8 words. Mix of verb-led, outcome-led, and contrarian. Number 1-10 and add a one-line rationale for each.`,
  },
  {
    slug: "domain-name-ideas",
    name: "Domain Name Ideas",
    tagline: "20 .com / .ai domain ideas worth buying.",
    description: "Short, brandable, likely-available combos.",
    inputLabel: "What's your product about?",
    inputPlaceholder: "e.g. AI for indie hacker launches",
    outputLabel: "20 Domain Ideas",
    prompt: (i) => `Suggest 20 short brandable domain names for: "${i}". Mix .com, .ai, .io extensions. Each max 12 characters before TLD. Likely-available combos only (avoid common dictionary words). Number 1-20.`,
  },
];

export const getTool = (slug: string) => tools.find((t) => t.slug === slug);