// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcujmvdgczkjxdstzhnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjdWptdmRnY3pranhkc3R6aG5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwMjQxMjAsImV4cCI6MjA5MDYwMDEyMH0.XVvba8xkOB-PuxxqcFVBL0OqD0nUReyKTVbyn9hMZlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});